# Generated by Django 3.2.11 on 2022-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20220201_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Город'),
        ),
    ]
